name: 'Pack & Publish Encrypted Artifact'
description: 'Pack repository, encrypt with password, and publish as artifact'

# ✅ FIX: Đổi từ inputs sang env vì workflow truyền qua env
# inputs:
#   artifact_password:
#     description: 'Password to encrypt the artifact'
#     required: true

runs:
  using: 'composite'
  steps:
    - name: Pack + encrypt repo artifact (always)
      id: pack-encrypt
      shell: bash
      run: |
        set -euo pipefail

        # ✅ FIX: Đọc từ env thay vì inputs
        ARTIFACT_PASSWORD="${ARTIFACT_PASS:-}"
        if [ -z "$ARTIFACT_PASSWORD" ]; then
          echo "❌ ERROR: Missing ARTIFACT_PASS environment variable"
          echo "Usage: Set env.ARTIFACT_PASS in workflow"
          exit 1
        fi

        # Tạo artifact name theo pattern GitHub
        ART_NAME="artifacts-${GITHUB_REPOSITORY//\//-}-${GITHUB_RUN_ID}"
        ART_DIR="$GITHUB_WORKSPACE/.artifacts"
        mkdir -p "$ART_DIR"

        # ✅ Tạo runtime debug files
        ENV_OUT="$GITHUB_WORKSPACE/runtime.env"
        ENV_TXT="$GITHUB_WORKSPACE/runtime.txt"

        env | sort > "$ENV_OUT"
        {
          echo "===== Build Info ====="
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Run Number: $GITHUB_RUN_NUMBER"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: ${GITHUB_REF#refs/heads/}"
          echo "Commit: $GITHUB_SHA"
          echo "Actor: $GITHUB_ACTOR"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo ""
          echo "===== Date ====="
          date -Is 2>/dev/null || date
          echo ""
          echo "===== System Info ====="
          uname -a 2>/dev/null || echo "uname not available"
          echo ""
          echo "===== Disk Usage ====="
          df -h 2>/dev/null || echo "df not available"
          echo ""
          echo "===== Memory ====="
          free -h 2>/dev/null || echo "free not available"
        } > "$ENV_TXT"

        ZIP_OUT="$ART_DIR/${ART_NAME}.zip"
        ENC_OUT="$ART_DIR/${ART_NAME}.zip.enc"

        echo "=========================================="
        echo "📦 PACKING REPOSITORY"
        echo "=========================================="
        echo "Working directory: $GITHUB_WORKSPACE"
        echo "Output: $ZIP_OUT"
        echo ""

        # ✅ ZIP với exclude patterns
        cd "$GITHUB_WORKSPACE"
        zip -r "$ZIP_OUT" . \
          -x ".git/*" \
          -x ".artifacts/*" \
          -x "*/node_modules/*" -x "node_modules/*" \
          -x "*/.venv/*" -x ".venv/*" \
          -x "*/venv/*" -x "venv/*" \
          -x "*/dist/*" -x "dist/*" \
          -x "*/build/*" -x "build/*" \
          -x "*/.cache/*" -x ".cache/*" \
          -x "*.tar.gz" -x "*.enc" -x "*.zip" || {
            echo "⚠️  ZIP command failed but continuing..."
          }

        echo ""
        if [ -f "$ZIP_OUT" ]; then
          echo "✅ ZIP created successfully"
          ZIP_SIZE=$(ls -lh "$ZIP_OUT" 2>/dev/null | awk '{print $5}' 2>/dev/null || echo "unknown")
          echo "Size: ${ZIP_SIZE}"
        else
          echo "❌ ERROR: ZIP file not created"
          exit 1
        fi

        echo ""
        echo "📋 ZIP contents preview (first 30 entries):"
        if command -v unzip >/dev/null 2>&1; then
          set +e
          ZIP_LIST=$(unzip -l "$ZIP_OUT" 2>/dev/null)
          ZIP_EXIT=$?
          set -e
          
          if [ $ZIP_EXIT -eq 0 ] && [ -n "$ZIP_LIST" ]; then
            echo "$ZIP_LIST" | head -n 33
          else
            echo "⚠️  Could not list ZIP contents"
          fi
        else
          echo "⚠️  unzip not available"
        fi

        echo ""
        echo "=========================================="
        echo "🔐 ENCRYPTING ARCHIVE"
        echo "=========================================="
        echo "Output: $ENC_OUT"
        echo ""

        openssl enc -aes-256-cbc -pbkdf2 -salt \
          -in "$ZIP_OUT" \
          -out "$ENC_OUT" \
          -pass env:ARTIFACT_PASSWORD

        # Xoá ZIP gốc
        rm -f "$ZIP_OUT"

        echo ""
        if [ -f "$ENC_OUT" ]; then
          echo "✅ Encryption completed"
          ENC_SIZE=$(ls -lh "$ENC_OUT" 2>/dev/null | awk '{print $5}' 2>/dev/null || echo "unknown")
          echo "Encrypted size: ${ENC_SIZE}"
          
          ENC_BYTES=$(stat -c%s "$ENC_OUT" 2>/dev/null || stat -f%z "$ENC_OUT" 2>/dev/null || echo "0")
          if [ "$ENC_BYTES" -gt 0 ]; then
            echo "✅ Encrypted file verified (${ENC_BYTES} bytes)"
          else
            echo "❌ ERROR: Encrypted file is empty!"
            exit 1
          fi
        else
          echo "❌ ERROR: Encrypted file not created"
          exit 1
        fi

        echo ""
        echo "=========================================="
        echo "📥 DECRYPT & EXTRACT GUIDE"
        echo "=========================================="
        echo "# Step 1: Decrypt"
        echo "openssl enc -d -aes-256-cbc -pbkdf2 \\"
        echo "  -in \"${ART_NAME}.zip.enc\" \\"
        echo "  -out repo.zip \\"
        echo "  -pass pass:\"YOUR_PASSWORD\""
        echo ""
        echo "# Step 2: Extract"
        echo "unzip repo.zip"
        echo "=========================================="

        # ✅ Export cho steps sau
        echo "ENC_OUT=$ENC_OUT" >> $GITHUB_OUTPUT
        echo "ART_NAME=$ART_NAME" >> $GITHUB_OUTPUT
        echo "ART_DIR=$ART_DIR" >> $GITHUB_OUTPUT
      continue-on-error: false  # ✅ Fail nếu có lỗi để dễ debug

    - name: Publish encrypted artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ steps.pack-encrypt.outputs.ART_NAME }}
        path: ${{ steps.pack-encrypt.outputs.ENC_OUT }}
        retention-days: 90
        if-no-files-found: error  # ✅ Fail rõ ràng nếu không có file

    - name: Show artifact info & links
      shell: bash
      if: always()
      run: |
        set -euo pipefail

        ART_NAME="${{ steps.pack-encrypt.outputs.ART_NAME }}"
        if [ -z "$ART_NAME" ]; then
          ART_NAME="artifacts-${GITHUB_REPOSITORY//\//-}-${GITHUB_RUN_ID}"
        fi

        RUN_ID="$GITHUB_RUN_ID"
        REPO_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"

        echo ""
        echo "=========================================="
        echo "✅ ARTIFACT PUBLISHED SUCCESSFULLY"
        echo "=========================================="
        echo "📦 Artifact name:"
        echo "   ${ART_NAME}"
        echo ""
        echo "🔗 Access Links:"
        echo "----------------------------------------"
        echo ""
        echo "📊 Workflow Run:"
        echo "   ${REPO_URL}/actions/runs/${RUN_ID}"
        echo ""
        echo "📦 Download Artifacts:"
        echo "   ${REPO_URL}/actions/runs/${RUN_ID}#artifacts"
        echo ""
        echo "=========================================="
        echo "⬇️  HOW TO DOWNLOAD & DECRYPT:"
        echo "=========================================="
        echo "1. Go to: ${REPO_URL}/actions/runs/${RUN_ID}"
        echo "2. Scroll to 'Artifacts' section"
        echo "3. Click '${ART_NAME}' to download"
        echo "4. Decrypt with command:"
        echo ""
        echo "openssl enc -d -aes-256-cbc -pbkdf2 \\"
        echo "  -in \"${ART_NAME}.zip.enc\" \\"
        echo "  -out repo.zip \\"
        echo "  -pass pass:\"YOUR_PASSWORD\""
        echo ""
        echo "5. Extract: unzip repo.zip"
        echo "=========================================="
